# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and Test

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and test (Node ${{ matrix.node.name }})
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        node:
          - { name: Current,      version: current }
          - { name: LTS,          version: lts/* }
    steps:
      - name: Build and test
        uses: myrotvorets/composite-actions/build-test-nodejs@d48d1c16e5782ea32f56fe24da600ca2028ed8b1 # master
        with:
          node-version: ${{ matrix.node.version }}
          registry-url: https://npm.pkg.github.com

  lint:
    name: Check code style
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      packages: read
    env:
      NO_UPDATE_NOTIFIER: 'true'
      NPM_CONFIG_FUND: '0'
      NPM_CONFIG_AUDIT: '0'
      SUPPRESS_SUPPORT: '1'
    steps:
      - name: Check out the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Node.js environment
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 'lts/*'
          registry-url: https://npm.pkg.github.com
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run postinstall scripts
        run: npm rebuild && npm run prepare --if-present

      - name: Check code style
        run: npm run lint

  typecheck:
    name: Check types
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      packages: read
    env:
      NO_UPDATE_NOTIFIER: 'true'
      NPM_CONFIG_FUND: '0'
      NPM_CONFIG_AUDIT: '0'
      SUPPRESS_SUPPORT: '1'
    steps:
      - name: Check out the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Node.js environment
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 'lts/*'
          registry-url: https://npm.pkg.github.com
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check types
        run: npm run typecheck
