name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Verify SONAR_TOKEN
        id: sonar_token
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo has_token=0 >> "${GITHUB_OUTPUT}";
          else
            echo has_token=1 >> "${GITHUB_OUTPUT}";
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run SonarCloud analysis
        if: steps.sonar_token.outputs.has_token == '1'
        uses: myrotvorets/composite-actions/node-sonarscan@master
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          test-script: 'test:sonarqube'
          registry-url: https://npm.pkg.github.com
